services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=gymtracker'
      - 'MYSQL_USER=gymtracker'
      - 'MYSQL_PASSWORD=gymtrackerpassword'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_PORT=3309'
    ports:
      - '3309:3306'
