spring:
  application:
    name: GymTrackerApp-workout
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/gymtrackerapp/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'


gymtrackerapp:
  gateway:
    base-url: http://localhost:8071/gymtrackerapp

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#        security.oauth2: DEBUG
#        security.oauth2.client: TRACE
#        security.oauth2.server.resource: TRACE


