spring:
  application:
    name: GymTrackerApp-workout
  config:
    import: optional:configserver:http://localhost:8070/
  profiles:
    active: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/gymtrackerapp/protocol/openid-connect/certs

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'


gymtrackerapp:
  gateway:
    base-url: http://localhost:8071/gymtrackerapp

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        security.oauth2: DEBUG
        security.oauth2.client: TRACE
        security.oauth2.server.resource: TRACE
