version: '3.8'
services:
  postgres:
    image: mysql:5.7
    container_name: GymTrackerApp-db
    environment:
      - MYSQL_ROOT_PASSWORD="secret"
      - MYSQL_USER="gymtracker"
      - MYSQL_PASSWORD="gymtrackerpassword"
      - MYSQL_DATABASE="GymTrackerApp"
    ports:
      - "3306:3307"
    networks:
      - GymTrackerApp-db-network

networks:
  GymTrackerApp-db-network:
    driver: bridge
